-- MySQL Script generated by MySQL Workbench
-- Sat Jun 24 16:19:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JPA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JPA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JPA` DEFAULT CHARACTER SET utf8 ;
USE `JPA` ;

-- -----------------------------------------------------
-- Table `JPA`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JPA`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JPA`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JPA`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cliente_Endereco_idx` (`Endereco_id` ASC),
  CONSTRAINT `fk_Cliente_Endereco`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `JPA`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
